name: Build Script

on:
  push:
    tags:
      - !"v*"
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod -R +x ./*

      - name: Clear build file if existe
        run: if [ -d "./build" ]; then rm -Rf ./build; fi

      - name: Clear eclipse file if existe
        run: if [ -d "./eclipse" ]; then rm -Rf ./eclipse; fi

      - name: Build
        run: |
          ./gradlew build

      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: true
          automatic_release_tag: dev
          title: "${{ github.event.head_commit.message }}"
          files: |
            **/build/libs/palatest-*.jar
