name: Build Script

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Make gradlew executable
        run: chmod -R +x ./*

      - name: Clear build file if existe
        run: if [ -d "./build" ]; then rm -Rf ./build; fi

      - name: Clear Gradle file if existe
        run: if [ -d "./.gradle" ]; then rm -Rf ./.gradle; fi

      - name: Clear eclipse file if existe
        run: if [ -d "./eclipse" ]; then rm -Rf ./eclipse; fi

      - name: Clear build file if existe
        run: if [ -d "./build" ]; then rm -Rf ./build; fi

      - name: Build
        run: |
          ./gradlew build

      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          prerelease: false
          automatic_release_tag: latest
          title: "${{ github.event.head_commit.message }}"
          files: |
            **/build/libs/palatest-*.jar
